version: "3.4"

services:

  patent-manager:
    image: ${REGISTRY}patent-manager:${PATENT_MANAGER_VERSION:-latest}
    #    deploy:
# Commented due to low resources on local
#      resources:
#        reservations:
#          cpus: '2'
#        limits:
#          memory: 2G
    ports:
      - 8082:8082
    environment:
      SPRING_PROFILES_ACTIVE: prod
    labels:
      kompose.service.type: nodeport
      nginx.ingress.kubernetes.io/rewrite-target: /$$1
      kompose.image-pull-policy: "IfNotPresent"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      start_period: 60s

  nlp-processor:
    image: ${REGISTRY}nlp-processor:${PATENT_MANAGER_VERSION:-latest}
    deploy:
      replicas: 2
# Commented due to low resources on local
#      resources:
#        reservations:
#          cpus: '2'
#        limits:
#          memory: 2G
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8081:8081
    labels:
      kompose.service.type: nodeport
      nginx.ingress.kubernetes.io/rewrite-target: /$$1
      kompose.image-pull-policy: "IfNotPresent"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      start_period: 60s

  ######################## Mongo ##############################
  mongo:
    image: mongo:4.0-xenial
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db
    labels:
      kompose.image-pull-policy: "Always"
      kompose.volume.size: 100Gi

  ##################### Kafka + Zookeeper #####################
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
    depends_on:
      - zookeeper
    labels:
      kompose.image-pull-policy: "Always"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    labels:
      kompose.image-pull-policy: "Always"

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - 9000:9000
    labels:
      kompose.image-pull-policy: "Always"

volumes:
  mongo-data:
